# Generated by Django 5.2.5 on 2026-07-25 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hours', models.IntegerField()),
                ('description', models.TextField()),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikes.bike')),
            ],
        ),
    ]
