# Generated by Django 5.2.5 on 2026-07-28 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0002_alter_bike_id_maintenancelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_type', models.CharField(choices=[('oil', 'Oil'), ('air_filter', 'Air Filter'), ('chain', 'Chain'), ('sprockets', 'Sprockets'), ('tires', 'Tires'), ('brake_pads', 'Brake Pads')], max_length=20)),
                ('date', models.DateField()),
                ('hours', models.IntegerField()),
                ('description', models.TextField()),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikes.bike')),
            ],
        ),
    ]
