# Generated by Django 5.2.5 on 2026-07-30 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0003_partservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancelog',
            name='bike',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='bikes.bike'),
        ),
    ]
